# Generated by Django 4.2.2 on 2024-03-11 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintable', '0002_category_subscribers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='connect_categories',
            new_name='category',
        ),
    ]
